language: elixir

script:
  - mix format --check-formatted
  - mix credo --strict
  - travis_wait 30 mix dialyzer --halt-exit-status
  - mix coveralls.travis

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report

matrix:
  include:
    - elixir: '1.8.2'
      otp_release: '21.3.8'
    - elixir: '1.9.4'
      otp_release: '22.0.7'
    - elixir: '1.10.2'
      otp_release: '22.3'

cache:
  directories:
    - _build
    - deps
